import { z } from "zod";

// Recurrence schema for nested recurrence settings
export const journalVoucherRecurrenceSchema = z.object({
  strProfileName: z
    .string()
    .min(1, { message: "Profile name is required" })
    .max(150, { message: "Profile name cannot exceed 150 characters" }),

  strRepeatType: z
    .string()
    .min(1, { message: "Repeat type is required" })
    .max(20, { message: "Repeat type cannot exceed 20 characters" }),

  intRepeatEveryValue: z
    .number()
    .int()
    .min(1, { message: "Repeat every value must be at least 1" }),

  strRepeatEveryUnit: z
    .string()
    .max(20, { message: "Repeat every unit cannot exceed 20 characters" })
    .nullable()
    .optional(),

  intRepeatOnDay: z
    .number()
    .int()
    .min(1, { message: "Repeat on day must be between 1 and 31" })
    .max(31, { message: "Repeat on day must be between 1 and 31" })
    .nullable()
    .optional(),

  strRepeatOnWeekday: z
    .string()
    .max(20, { message: "Weekday cannot exceed 20 characters" })
    .nullable()
    .optional(),

  strCustomFrequencyJson: z.string().nullable().optional(),

  dStartDate: z.string().min(1, { message: "Start date is required" }),

  dEndDate: z.string().nullable().optional(),

  bolNeverExpires: z.boolean(),
});

export type JournalVoucherRecurrenceFormValues = z.infer<
  typeof journalVoucherRecurrenceSchema
>;

// Journal Voucher schema for form validation (Create/Update)
// Note: strJournal_VoucherNo and intJournal_VoucherSeqNo are auto-generated by backend
export const journalVoucherSchema = z.object({
  dJournal_VoucherDate: z
    .string()
    .min(1, { message: "Voucher date is required" }),

  strRefNo: z
    .string()
    .max(100, { message: "Reference number cannot exceed 100 characters" })
    .optional()
    .or(z.literal("")),

  strNotes: z
    .string()
    .min(1, { message: "Notes are required" })
    .max(500, { message: "Notes cannot exceed 500 characters" }),

  strCurrencyTypeGUID: z
    .string({ required_error: "Currency is required" })
    .uuid({ message: "Invalid currency type" }),

  dblExchangeRate: z
    .number()
    .nonnegative({ message: "Exchange rate must be non-negative" })
    .default(0)
    .optional(),

  strStatus: z
    .string()
    .min(1, { message: "Status is required" })
    .max(20, { message: "Status cannot exceed 20 characters" }),

  bolIsJouranl_Adjustement: z.boolean(),
  
  strReportingMethod: z
    .string()
    .min(1, { message: "Reporting method is required" }),

  // Optional recurrence settings
  recurrence: journalVoucherRecurrenceSchema.nullable().optional(),
});

export type JournalVoucherFormValues = z.infer<typeof journalVoucherSchema>;

// Change Status schema
export const changeStatusSchema = z.object({
  strStatus: z
    .string()
    .min(1, { message: "Status is required" })
    .max(20, { message: "Status cannot exceed 20 characters" }),

  strRejectedReason: z
    .string()
    .max(500, { message: "Rejection reason cannot exceed 500 characters" })
    .nullable()
    .optional(),
});

export type ChangeStatusFormValues = z.infer<typeof changeStatusSchema>;
