-- Check database structure
USE MasterDB;
GO

PRINT 'All Schemas in MasterDB:';
SELECT SCHEMA_NAME 
FROM INFORMATION_SCHEMA.SCHEMATA
ORDER BY SCHEMA_NAME;

PRINT '';
PRINT 'All Tables containing "Activity":';
SELECT 
    TABLE_SCHEMA,
    TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE '%Activity%'
ORDER BY TABLE_SCHEMA, TABLE_NAME;

PRINT '';
PRINT 'MstActivity columns (all schemas):';
SELECT 
    TABLE_SCHEMA,
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'MstActivity'
ORDER BY TABLE_SCHEMA, ORDINAL_POSITION;
